package team.gif.friendscheduler.model;

public enum FriendshipStatus {
	
	AWAITING_SMALLER_ID_APPROVAL, AWAITING_LARGER_ID_APPROVAL, FRIENDS,
	LARGER_BLOCKED_SMALLER, SMALLER_BLOCKED_LARGER, BOTH_BLOCKED
	
}
